name: CI

on:
  push:
    branches: [ main ]

jobs:
  setup_and_build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          chmod +x Scripts/install.sh
          sudo ./Scripts/install.sh

      - name: Build Project | All
        run: |
          mkdir -p build && cd build
          cmake ..
          cmake --build .
