name: CI

on:
  push:
    branches: [ main ]

jobs:
  setup_and_build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          chmod +x Scripts/install.sh
          sudo ./Scripts/install.sh

      - name: Build Project | Release
        run: |
          mkdir -p build && cd build
          cmake .. -DCMAKE_BUILD_TYPE=Debug -DCMAKE_C_COMPILER=/usr/bin/clang-11 -DCMAKE_CXX_COMPILER=/usr/bin/clang++-11
          cmake --build .

      - name: Build Project | Debug
        run: |
          mkdir -p build && cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=/usr/bin/clang-11 -DCMAKE_CXX_COMPILER=/usr/bin/clang++-11
          cmake --build .
